### ISSUE TITLE
capabilities overlap

### ISSUE THREAD

**Issue by loriab** [lilyminium/psiresp#104]
Hi @lilyminium, It's nice to see this repo -- I wasn't aware of it. I'm pretty close to getting psi4 up on c-f https://github.com/conda-forge/staged-recipes/pull/22328, and I had planned to package Asem's https://github.com/cdsgroup/resp . Could you give me an idea of the functionality overlap between psiresp and Asem's repo? If there's nothing missing and you're already maintaining this one with qcarchive integration, perhaps I don't need to package the other. Thanks!

**Comment by loriab** [comment]
Found the JOSS article and mention of inter-mol constraints that Asem's doesn't have. That answers most of my question, thanks, but if there's any other compare/contrast that you know of, I'd be glad to hear it.

**Comment by lilyminium** [comment]
Thanks @loriab (and sorry for the delay in answering, I've realised that I'm not getting notifications from this repo). I was aware of Asem's repo when I submitted to JOSS, so that about covers the differences. Maybe also that there's some symmetrisation code now so symmetric groups should get equal charges -- I don't recall if his had that.
